before_script:
  # Update package repository and install necessary tools
  - yum update -y
  - yum install -y make gcc libcmocka-dev

build:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - bin/
    expire_in: 1 hour

test:
  stage: test
  script:
    - make test
