image: gcc

stages:
  - build
  - test

before_script:
  # Use non-interactive frontend to avoid user prompts
  - export DEBIAN_FRONTEND=noninteractive
  # Update and install dependencies
  - apt-get update && apt-get install -y build-essential libcmocka-dev

build:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - bin/
    expire_in: 1 hour
  only:
    - main
    - dev

test:
  stage: test
  script:
    - make test
  only:
    - main
    - dev
